import Head from 'next/head'
import Image from 'next/image'
import Grid from '../components/Grid'
import Info from '../components/Info'
import Intro from '../components/Intro'
import Subscribe from '../components/Subscribe'
import Vacation from '../components/Vacation'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Intro />
      <Vacation />
      <Info />
      <Grid />
      <Subscribe />
    </div>
  )
}
